stages:
  - build
  - test
# Linux builds
build_linux_gcc:
  stage: build
  tags:
    - x86
  image: ubuntu
  before_script:
    - apt update && apt install -y build-essential curl autoconf automake libtool 
  script:
    - gcc --version
    - autoreconf -if
    - ./configure
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - libovvc/.libs/libovvc.so*
      - examples/.libs/dectest
      - examples/dectest

passing_conf_gcc:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc
  before_script:
    - apt update && apt install -y curl
  script:
    - export OVDEC=$(pwd)/examples/dectest
    - export OVSTREAM=/test_bitstreams
    - ./CI/dlvideobin https://nasext-vaader.insa-rennes.fr/ietr-vaader/OVVC/conf_stream/ ${OVSTREAM}/conf_stream/ --no_md5
    - ./CI/ovnreg ./CI/conf.vmd5
  artifacts:
    when: on_failure
    paths:
      - .ovnreg_*

failing_conf_gcc:
  allow_failure: true
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc
  before_script:
    - apt update && apt install -y curl
  script:
    - export OVDEC=$(pwd)/examples/dectest
    - export OVSTREAM=/test_bitstreams
    - grep "^[#;]" CI/conf.vmd5 | sed 's/# //g' > CI/fail.vmd5
    - ./CI/dlvideobin https://nasext-vaader.insa-rennes.fr/ietr-vaader/OVVC/conf_stream/ ${OVSTREAM}/conf_stream/ --no_md5
    - ./CI/ovnreg ./CI/fail.vmd5 --no_cleanup --keep_fail
  artifacts:
    when: on_failure
    paths:
      - .ovnreg_*

# MAC OS builds
build_macos_gcc:
  stage: build
  tags:
    - MACOS
  script:
    - gcc --version
    - autoreconf -if
    - ./configure
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - libovvc/.libs/libovvc*.dylib
      - examples/.libs/dectest
      - examples/dectest

passing_conf_macos_gcc:
  stage: test
  tags:
    - MACOS
  dependencies:
    - build_macos_gcc
  script:
    - export OVDEC=$(pwd)/examples/dectest
    - export OVSTREAM=/Users/gugautie/test_bitstreams
    - ./CI/dlvideobin https://nasext-vaader.insa-rennes.fr/ietr-vaader/OVVC/conf_stream/ ${OVSTREAM}/conf_stream/ --no_md5
    - ./CI/ovnreg ./CI/conf.vmd5
  artifacts:
    when: on_failure
    paths:
      - .ovnreg_*

failing_conf_macos_gcc:
  allow_failure: true
  stage: test
  tags:
    - MACOS
  dependencies:
    - build_macos_gcc
  script:
    - export OVDEC=$(pwd)/examples/dectest
    - export OVSTREAM=/Users/gugautie/test_bitstreams
    - grep "^[#;]" CI/conf.vmd5 | sed 's/# //g' > CI/fail.vmd5
    - ./CI/dlvideobin https://nasext-vaader.insa-rennes.fr/ietr-vaader/OVVC/conf_stream/ ${OVSTREAM}/conf_stream/ --no_md5
    - ./CI/ovnreg ./CI/fail.vmd5 --no_cleanup --keep_fail
  artifacts:
    when: on_failure
    paths:
      - .ovnreg_*
